Fix format() with string input error
The documentation on http://activemerchant.org uses strings when instantiating `ActiveMerchant::Billing::CreditCard`. However, if '08' or '09' is used, it can cause an error as sprintf assumes it is doing an octal conversion.

Failing test case:

```
test_should_format_number_by_rule(CreditCardFormattingTest):
ArgumentError: invalid value for Integer(): "08"
    /Users/gabebug/github/active_merchant/lib/active_merchant/billing/credit_card_formatting.rb:13:in `sprintf'
    /Users/gabebug/github/active_merchant/lib/active_merchant/billing/credit_card_formatting.rb:13:in `format'
    /Users/gabebug/github/active_merchant/test/unit/credit_card_formatting_test.rb:17:in `test_should_format_number_by_rule'
    /Users/gabebug/.rvm/gems/ruby-1.9.3-p286/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:28:in `run'
```